name: Build and push image to ECR

on:
  push:
    branches:
      - "*"           # build for all branches (good for testing PRs)

    paths:
      - "src/**"
      - "Dockerfile"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: demo/lfb
  AWS_ACCOUNT_ID: 202279973546
  CLUSTER_NAME: eks-cluster-oidc
  NAMESPACE: production

jobs:

# ---------------- BUILD ----------------
  build:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build.outputs.image_uri }}
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202279973546:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Generate SHA tag
        id: meta
        run: echo "tag=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Build & push image
        id: build
        run: |
          IMAGE_TAG="${{ steps.meta.outputs.tag }}"
          IMAGE_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG}"

          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

          echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"