name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - '*'   # all branches
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      # AWS_REGION: ap-south-1
      # ECR_REPOSITORY: demo/lfb
      AWS_REGION: us-east-1
      ECR_REPOSITORY: demo/lfb
      AWS_ACCOUNT_ID: 202279973546

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202279973546:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push $IMAGE_URI

      - name: Tag latest on main
        if: github.ref == 'refs/heads/main'
        run: |
          LATEST_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
          docker tag $IMAGE_URI $LATEST_URI
          docker push $LATEST_URI
