apiVersion: v1
kind: Service
metadata:
  name: lfb-service
  namespace: {{ .Values.namespace }}
  labels:
    app: lfb
spec:
  type: {{ .Values.service.type }}
  selector:
    app: lfb
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}